<?php

namespace Database\Seeders;

use App\Models\Contact;
use Illuminate\Database\Seeder;

class ContactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Очищаем таблицу перед заполнением
        Contact::truncate();

        $contacts = [
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Генеральный директор*',
                'position_kz' => 'Бас директор',
                'full_name' => 'Мынтурганов Канагат Нурымович',
                'phone_number' => '+7 729 349 31 93',
                'internal_number' => '193',
                'mobile_number' => '+771-088-0034',
                'email' => 'K.Mynturganov@oms.kmg.kz',
                'status' => true,
                'sort' => 1,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Заместитель генерального директора по производству',
                'position_kz' => 'Өндіріс жөніндегі бас директордың орынбасары',
                'full_name' => 'Салихов Абай Турганович',
                'phone_number' => '+7 729 349 32 00',
                'internal_number' => '200',
                'mobile_number' => '+777-111-6898',
                'email' => 'A.Salihov@oms.kmg.kz',
                'status' => true,
                'sort' => 2,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Заместитель генерального директора по экономике и финансам*',
                'position_kz' => 'Экономика және қаржы жөніндегі бас директордың орынбасары',
                'full_name' => 'Елеусинов Мурат Еркинулы',
                'phone_number' => '+7 729 349 31 79',
                'internal_number' => '179',
                'mobile_number' => '+701-544-2674',
                'email' => 'M.Eleusinov1@oms.kmg.kz',
                'status' => true,
                'sort' => 3,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Заместитель генерального директора  по обеспечению производства',
                'position_kz' => 'Өндірісті қамтамасыз ету жөніндегі бас директордың орынбасары',
                'full_name' => 'Бекмамбетов Сарсенбай Утегенович',
                'phone_number' => '+7 729 349 32 32',
                'internal_number' => '232',
                'mobile_number' => '+777-377-7475',
                'email' => 'S.Bekmambetov@oms.kmg.kz',
                'status' => true,
                'sort' => 4,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Заместитель генерального директора  по управлению персоналом, оплате труда и социальным вопросам',
                'position_kz' => 'Персоналды басқару, еңбекақы төлеу және әлеуметтік мәселелер жөніндегі бас директордың орынбасары',
                'full_name' => 'Ермаганбетов Нурым Амантаевич',
                'phone_number' => '+7 729 349 31 78',
                'internal_number' => '178',
                'mobile_number' => '+777-057-9670',
                'email' => 'N.Ermaganbetov@oms.kmg.kz',
                'status' => true,
                'sort' => 5,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Приемная Ген. директор',
                'position_kz' => 'Бас директордың қабылдау бөлмесі',
                'full_name' => 'Офис менеджер',
                'phone_number' => '+7 729 349 31 70',
                'internal_number' => '170',
                'mobile_number' => '+701-684-2223',
                'email' => 'Info4@oms.kmg.kz',
                'status' => true,
                'sort' => 6,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Офис менеджер',
                'position_kz' => 'Офис менеджері',
                'full_name' => 'Офис менеджер',
                'phone_number' => '+7 729 349 31 38',
                'internal_number' => '138',
                'mobile_number' => '+778-121-5528',
                'email' => 'Info11@oms.kmg.kz',
                'status' => true,
                'sort' => 7,
            ],
            [
                'category_ru' => 'Руководство',
                'category_kz' => 'Басшылық',
                'position_ru' => 'Заведующий канцелярией',
                'position_kz' => 'Кеңсе меңгерушісі',
                'full_name' => 'Абдуллаев Аскер Рафаэльевич',
                'phone_number' => '+7 729 349 32 25',
                'internal_number' => '225',
                'mobile_number' => '+707-778-8366',
                'email' => 'A.Abdullayev1@oms.kmg.kz',
                'status' => true,
                'sort' => 8,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Руководитель службы',
                'position_kz' => 'Қызмет басшысы',
                'full_name' => 'Базарбаев Нуржан Акмуратович',
                'phone_number' => '+7 729 349 32 23',
                'internal_number' => '223',
                'mobile_number' => '+777-377-74-60',
                'email' => 'N.Bazarbayev@oms.kmg.kz',
                'status' => true,
                'sort' => 9,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Заместитель руководителя службы',
                'position_kz' => 'Қызмет басшысының орынбасары',
                'full_name' => 'Абишаев Сагидолла Орынбаевич',
                'phone_number' => '+7 729 349 31 55',
                'internal_number' => '155',
                'mobile_number' => '+701-526-1420',
                'email' => 'S.Abishaev@oms.kmg.kz',
                'status' => true,
                'sort' => 10,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Инженер-технолог',
                'position_kz' => 'Инженер-технолог',
                'full_name' => 'Дильмагамбетов Бауыржан Эсембаевич',
                'phone_number' => '+7 729 349 32 04',
                'internal_number' => '204',
                'mobile_number' => '+701-312-3412',
                'email' => 'B.Dilmagambetov@oms.kmg.kz',
                'status' => true,
                'sort' => 11,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Ведущий инженер (КРС)',
                'position_kz' => 'Ведущий инженер (КРС)',
                'full_name' => 'Такенов Бексат Сармурзаевич',
                'phone_number' => '+7 729 349 31 97',
                'internal_number' => '197',
                'mobile_number' => '+777-550-4151',
                'email' => 'B.Takenov@oms.kmg.kz',
                'status' => true,
                'sort' => 12,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Ведущий инженер по транспорту',
                'position_kz' => 'Ведущий инженер по транспорту',
                'full_name' => 'Бекжан Бекарыс Бұқарбайұлы',
                'phone_number' => '+7 729 349 31 68',
                'internal_number' => '168',
                'mobile_number' => '+777-5994251',
                'email' => 'B.Bekzhan@oms.kmg.kz',
                'status' => true,
                'sort' => 13,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Инженер-технолог',
                'position_kz' => 'Инженер-технолог',
                'full_name' => 'Толесинов Алмат Бакытжанулы',
                'phone_number' => '+7 729 349 32 33',
                'internal_number' => '233',
                'mobile_number' => '+778-113-9133',
                'email' => 'A.Tolesinov@oms.kmg.kz',
                'status' => true,
                'sort' => 14,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Инженер (КРС) 1 категории',
                'position_kz' => 'Инженер (КРС) 1 категории',
                'full_name' => 'Бердимуратов Сабит Джылкыбаевич',
                'phone_number' => '+7 729 349 31 46',
                'internal_number' => '146',
                'mobile_number' => '+778-568-4182',
                'email' => 'S.Berdimuradov@oms.kmg.kz',
                'status' => true,
                'sort' => 15,
            ],
            [
                'category_ru' => 'Производственно-технологический  служба',
                'category_kz' => 'Өндірістік-технологиялық қызмет',
                'position_ru' => 'Вед.инженер (по строительству)',
                'position_kz' => 'Вед.инженер (по строительству)',
                'full_name' => 'Жұбантұров Бакдәулет Қанибекұлы',
                'phone_number' => '+7 729 349 32 14',
                'internal_number' => '214',
                'mobile_number' => '+776-600-6464',
                'email' => 'B.Zhubanturov@oms.kmg.kz',
                'status' => true,
                'sort' => 16,
            ],
            [
                'category_ru' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'category_kz' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Урбесинов Оркен Гусмадинович',
                'phone_number' => '+7 729 349 31 77',
                'internal_number' => '177',
                'mobile_number' => '+701-369-6600',
                'email' => 'O.Urbisinov@oms.kmg.kz',
                'status' => true,
                'sort' => 17,
            ],
            [
                'category_ru' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'category_kz' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'position_ru' => 'Ведущий инженер',
                'position_kz' => 'Жетекші инженер',
                'full_name' => 'Оспанов Болатбек Дуйсенбекович',
                'phone_number' => '+7 729 349 32 12',
                'internal_number' => '212',
                'mobile_number' => '+702-999-1230',
                'email' => 'B.Ospanov1@oms.kmg.kz',
                'status' => true,
                'sort' => 18,
            ],
            [
                'category_ru' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'category_kz' => 'Отдел новых технологий, качества и управления рисками (ОНТ,КиУР)',
                'position_ru' => 'Инженер',
                'position_kz' => 'Инженер',
                'full_name' => 'Кенбаев Серик Муратович',
                'phone_number' => '+7 729 349 31 72',
                'internal_number' => '172',
                'mobile_number' => '+702-397-9292',
                'email' => 'N.Kokushev@oms.kmg.kz',
                'status' => true,
                'sort' => 19,
            ],
            [
                'category_ru' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'category_kz' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Тураров Ерназар Джангабергенович',
                'phone_number' => '+7 729 349 31 61',
                'internal_number' => '161',
                'mobile_number' => '+777-111-6781',
                'email' => 'E.Turarov@oms.kmg.kz',
                'status' => true,
                'sort' => 20,
            ],
            [
                'category_ru' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'category_kz' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'position_ru' => 'Заместитель начальника отдела',
                'position_kz' => 'Заместитель начальника отдела',
                'full_name' => 'Бисенбиева Шынар Амалбековна',
                'phone_number' => '+7 729 349 32 02',
                'internal_number' => '202',
                'mobile_number' => '+701-526-1367',
                'email' => 'Sh.Bissenbiyeva@oms.kmg.kz',
                'status' => true,
                'sort' => 21,
            ],
            [
                'category_ru' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'category_kz' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'position_ru' => 'Ведущий экономист',
                'position_kz' => 'Ведущий экономист',
                'full_name' => 'Бегенишов Мурат Мусаулы',
                'phone_number' => '+7 729 349 31 85',
                'internal_number' => '185',
                'mobile_number' => '+777-362-9977',
                'email' => 'M.Begenishov@oms.kmg.kz',
                'status' => true,
                'sort' => 22,
            ],
            [
                'category_ru' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'category_kz' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'position_ru' => 'Ведущий экономист',
                'position_kz' => 'Ведущий экономист',
                'full_name' => 'Сатыбалдиева Сагира Бердыевна',
                'phone_number' => '+7 729 349 31 76',
                'internal_number' => '176',
                'mobile_number' => '+775-335-6660',
                'email' => 'S.Utesinova@oms.kmg.kz',
                'status' => true,
                'sort' => 23,
            ],
            [
                'category_ru' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'category_kz' => 'Отдел бюджетирования планирования и экономического анализа (ОБПиЭА)',
                'position_ru' => 'И.O.Экономист 2 категории',
                'position_kz' => 'И.O.Экономист 2 категории',
                'full_name' => 'Ишанбаева Алмагул Оспановна',
                'phone_number' => '+7 729 349 32 19',
                'internal_number' => '213',
                'mobile_number' => '+701-484-5992',
                'email' => 'A.Ishanbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 24,
            ],
            [
                'category_ru' => 'Отдел правового обеспечения (ОПО)',
                'category_kz' => 'Отдел правового обеспечения (ОПО)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Айтжанов Ержан Жанадилович',
                'phone_number' => '+7 729 349 31 63',
                'internal_number' => '163',
                'mobile_number' => '+777-057-9693',
                'email' => 'E.Aitzhanov@oms.kmg.kz',
                'status' => true,
                'sort' => 25,
            ],
            [
                'category_ru' => 'Отдел правового обеспечения (ОПО)',
                'category_kz' => 'Отдел правового обеспечения (ОПО)',
                'position_ru' => 'Ведущий юрисконсульт',
                'position_kz' => 'Ведущий юрисконсульт',
                'full_name' => 'Исатаев Асылбек Бакытович',
                'phone_number' => '+7 729 349 31 95',
                'internal_number' => '195',
                'mobile_number' => '+777-781-5579',
                'email' => 'A.Isataev1@oms.kmg.kz',
                'status' => true,
                'sort' => 26,
            ],
            [
                'category_ru' => 'Отдел правового обеспечения (ОПО)',
                'category_kz' => 'Отдел правового обеспечения (ОПО)',
                'position_ru' => 'Юрисконсульт',
                'position_kz' => 'Юрисконсульт',
                'full_name' => 'Жолтаев Аманжол Аралбайұлы',
                'phone_number' => '',
                'internal_number' => '',
                'mobile_number' => '',
                'email' => '',
                'status' => true,
                'sort' => 27,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Казикулов Есбосын Каракбаевич',
                'phone_number' => '+7 729 349 31 60',
                'internal_number' => '160',
                'mobile_number' => '+777-599-4252',
                'email' => 'E.Kazikulov@oms.kmg.kz',
                'status' => true,
                'sort' => 28,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Зам. начальника отдела',
                'position_kz' => 'Зам. начальника отдела',
                'full_name' => 'Таласбаев Мырзаболат Нурбергенович',
                'phone_number' => '+7 729 349 32 10',
                'internal_number' => '210',
                'mobile_number' => '+702-296-6426',
                'email' => 'M.Talasbayev@oms.kmg.kz',
                'status' => true,
                'sort' => 29,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Вед. экономист по труду',
                'position_kz' => 'Вед. экономист по труду',
                'full_name' => 'Жұмабаева Мөлдір Мақықызы',
                'phone_number' => '+7 729 349 31 56',
                'internal_number' => '156',
                'mobile_number' => '+777-550-5030',
                'email' => 'M.Zhumabaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 30,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Вед. специалист по кадрам',
                'position_kz' => 'Вед. специалист по кадрам',
                'full_name' => 'Аралбаева Санбиби Аралбаевна',
                'phone_number' => '+7 729 349 32 11',
                'internal_number' => '211',
                'mobile_number' => '+701-424-74-25',
                'email' => 'S.Aralbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 31,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Специалист по кадрам',
                'position_kz' => 'Специалист по кадрам',
                'full_name' => 'Чанбаева Гулзия Исабаевна',
                'phone_number' => '+7 729 349 31 49',
                'internal_number' => '149',
                'mobile_number' => '+702-256-5638',
                'email' => 'G.Chanbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 32,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Специалист по кадрам',
                'position_kz' => 'Специалист по кадрам',
                'full_name' => 'Баймуналова Аклес Кулжабаевна',
                'phone_number' => '+7 729 349 31 47',
                'internal_number' => '147',
                'mobile_number' => '+702-893-6273',
                'email' => 'A.Baimunalova@oms.kmg.kz',
                'status' => true,
                'sort' => 33,
            ],
            [
                'category_ru' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'category_kz' => 'Отдел по управлению персоналом и оплате труда (ОПУПиОТ)',
                'position_ru' => 'Специалист по кадрам',
                'position_kz' => 'Специалист по кадрам',
                'full_name' => 'Мысаева Шырын Турарбековна',
                'phone_number' => '+7 729 349 31 48',
                'internal_number' => '148',
                'mobile_number' => '+701-459-6511',
                'email' => 'Sh.Mysaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 34,
            ],
            [
                'category_ru' => 'Группа безопасности',
                'category_kz' => 'Группа безопасности',
                'position_ru' => 'Руководитель группы',
                'position_kz' => 'Руководитель группы',
                'full_name' => 'Балгожаев Мендибай Абиевич',
                'phone_number' => '+7 729 349 31 39',
                'internal_number' => '139',
                'mobile_number' => '+775-924-1730',
                'email' => 'M.Balgozhayev@oms.kmg.kz',
                'status' => true,
                'sort' => 35,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Главный бухгалтер',
                'position_kz' => 'Бас бухгалтер',
                'full_name' => 'Кушкамбаева Айша Ниязовна',
                'phone_number' => '+7 729 349 31 83',
                'internal_number' => '183',
                'mobile_number' => '+777-057-7281',
                'email' => 'A.Kushkambaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 36,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Зам.главного бухгалтера',
                'position_kz' => 'Зам.главного бухгалтера',
                'full_name' => 'Бекбаев Алимжан Кенжебаевич',
                'phone_number' => '+7 729 349 31 58',
                'internal_number' => '158',
                'mobile_number' => '+705-883-5460',
                'email' => 'A.Bekbaev@oms.kmg.kz',
                'status' => true,
                'sort' => 37,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Ведущий бухгалтер****',
                'position_kz' => 'Ведущий бухгалтер****',
                'full_name' => 'Кожанепесова Гульшат Маткировна',
                'phone_number' => '+7 729 349 31 53',
                'internal_number' => '153',
                'mobile_number' => '+702-215-1403',
                'email' => 'G.Kozhanepesova1@oms.kmg.kz',
                'status' => true,
                'sort' => 38,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Старший бухгалтер*****',
                'position_kz' => 'Старший бухгалтер*****',
                'full_name' => 'Бегимова Гульмира Булатовна',
                'phone_number' => '+7 729 349 31 57',
                'internal_number' => '157',
                'mobile_number' => '+775-445-7004',
                'email' => 'G.Begimova@oms.kmg.kz',
                'status' => true,
                'sort' => 39,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Старший бухгалтер',
                'position_kz' => 'Старший бухгалтер',
                'full_name' => 'Өтебай Бұлбұл Айтқалиқызы',
                'phone_number' => '+7 729 349 31 52',
                'internal_number' => '152',
                'mobile_number' => '+701-216-3395',
                'email' => 'B.Otebai@oms.kmg.kz',
                'status' => true,
                'sort' => 40,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Бухгалтер 1 категории',
                'position_kz' => 'Бухгалтер 1 категории',
                'full_name' => 'Дуйсенбаева Кумусай Албашовна',
                'phone_number' => '+7 729 349 31 86',
                'internal_number' => '186',
                'mobile_number' => '+702-356-5686',
                'email' => 'K.Duisenbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 41,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Бухгалтер 1 категории',
                'position_kz' => 'Бухгалтер 1 категории',
                'full_name' => 'Джандулаева Алия Базарбаевна',
                'phone_number' => '+7 729 349 31 62',
                'internal_number' => '162',
                'mobile_number' => '+705-883-0041',
                'email' => 'A.Dzhandulaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 42,
            ],
            [
                'category_ru' => 'Бухгалтерия',
                'category_kz' => 'Бухгалтерия',
                'position_ru' => 'Бухгалтер 1 категории',
                'position_kz' => 'Бухгалтер 1 категории',
                'full_name' => 'Кыдырбаева Айжан Есмурзаевна',
                'phone_number' => '+7 729 349 31 54',
                'internal_number' => '154',
                'mobile_number' => '+701-507-7810',
                'email' => 'A.Kydyrbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 43,
            ],
            [
                'category_ru' => 'Группа по АСУПиИТ',
                'category_kz' => 'Группа по АСУПиИТ',
                'position_ru' => 'Руководитель группы',
                'position_kz' => 'Руководитель группы',
                'full_name' => 'Новетов Есен Нысанбаевич',
                'phone_number' => '+7 729 349 32 20',
                'internal_number' => '220',
                'mobile_number' => '+700-407-5565',
                'email' => 'Y.Novetov@oms.kmg.kz',
                'status' => true,
                'sort' => 44,
            ],
            [
                'category_ru' => 'Группа по АСУПиИТ',
                'category_kz' => 'Группа по АСУПиИТ',
                'position_ru' => 'Старший инженер (АСУП)',
                'position_kz' => 'Старший инженер (АСУП)',
                'full_name' => 'Турлиев Айбек Айдарулы',
                'phone_number' => '',
                'internal_number' => '',
                'mobile_number' => '+775-214-2901',
                'email' => 'A.Turliyev@oms.kmg.kz',
                'status' => true,
                'sort' => 45,
            ],
            [
                'category_ru' => 'Группа по АСУПиИТ',
                'category_kz' => 'Группа по АСУПиИТ',
                'position_ru' => 'Инженер (ИТ по связи)',
                'position_kz' => 'Инженер (ИТ по связи)',
                'full_name' => 'Нурбаев Акылбек Бердимуратович',
                'phone_number' => '+7 729 349 32 80',
                'internal_number' => '180',
                'mobile_number' => '+776-838-5212',
                'email' => '',
                'status' => true,
                'sort' => 46,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Баржиков Ербол Абаевич',
                'phone_number' => '+7 729 349 31 87',
                'internal_number' => '187',
                'mobile_number' => '+771-221-3460',
                'email' => 'E.Barzhikov@oms.kmg.kz',
                'status' => true,
                'sort' => 47,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Зам. начальника отдела',
                'position_kz' => 'Зам. начальника отдела',
                'full_name' => 'Текебаев Нурлыбек Кадырович',
                'phone_number' => '+7 729 349 31 50',
                'internal_number' => '150',
                'mobile_number' => '+777-599-4257',
                'email' => 'N.Tekebaev@oms.kmg.kz',
                'status' => true,
                'sort' => 48,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Ведущий инженер-энергетик',
                'position_kz' => 'Ведущий инженер-энергетик',
                'full_name' => 'Жайлауов Максат Айтбаевич',
                'phone_number' => '+7 729 349 31 71',
                'internal_number' => '171',
                'mobile_number' => '',
                'email' => 'M.Zhailauov@oms.kmg.kz',
                'status' => true,
                'sort' => 49,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Ведущий механик',
                'position_kz' => 'Ведущий механик',
                'full_name' => 'Караев Сагингали Едилбаевич',
                'phone_number' => '+7 729 349 32 03',
                'internal_number' => '203',
                'mobile_number' => '+777-781-5574',
                'email' => 'S.Karaev@oms.kmg.kz',
                'status' => true,
                'sort' => 50,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Инженер -механик',
                'position_kz' => 'Инженер -механик',
                'full_name' => 'Алдабергенова Айша Нуркасымовна',
                'phone_number' => '+7 729 349 31 94',
                'internal_number' => '194',
                'mobile_number' => '+702-571-4953',
                'email' => 'Ai.Aldabergenova@oms.kmg.kz',
                'status' => true,
                'sort' => 51,
            ],
            [
                'category_ru' => 'Механико-энергетический отдел (МЭО)',
                'category_kz' => 'Механико-энергетический отдел (МЭО)',
                'position_ru' => 'Инженер -механик',
                'position_kz' => 'Инженер -механик',
                'full_name' => 'Рамазанова Нургуль Коженовна',
                'phone_number' => '+7 729 349 31 96',
                'internal_number' => '196',
                'mobile_number' => '+702-758-7542',
                'email' => 'N.Ramazanova@oms.kmg.kz',
                'status' => true,
                'sort' => 52,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Абулгазиев Кайрат Калпакович',
                'phone_number' => '+7 729 349 31 42',
                'internal_number' => '142',
                'mobile_number' => '+776-003-3012',
                'email' => 'K.Abulgaziev@oms.kmg.kz',
                'status' => true,
                'sort' => 53,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Зам. начальника отдела',
                'position_kz' => 'Зам. начальника отдела',
                'full_name' => 'Урпеков Нурболат Айткожаевич',
                'phone_number' => '+7 729 349 31 99',
                'internal_number' => '199',
                'mobile_number' => '+777-057-9692',
                'email' => 'N.Urpekov@oms.kmg.kz',
                'status' => true,
                'sort' => 54,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Вед.инж. по охране труда и технике безопасности',
                'position_kz' => 'Вед.инж. по охране труда и технике безопасности',
                'full_name' => 'Джамбулов Серик Ахмедович',
                'phone_number' => '+7 729 349 31 44',
                'internal_number' => '144',
                'mobile_number' => '+777-703-0400',
                'email' => 'S.Dzhambulov@oms.kmg.kz',
                'status' => true,
                'sort' => 55,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Вед.инж. по охране окружающей среды',
                'position_kz' => 'Вед.инж. по охране окружающей среды',
                'full_name' => 'Молбаева Айнур Жарыевна',
                'phone_number' => '+7 729 349 31 45',
                'internal_number' => '145',
                'mobile_number' => '+775-315-4540',
                'email' => 'A.Molbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 56,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Специалист по гражданской обороне',
                'position_kz' => 'Специалист по гражданской обороне',
                'full_name' => 'Ақжолов Нұрсұлтан Есетұлы',
                'phone_number' => '+7 729 349 31 43',
                'internal_number' => '143',
                'mobile_number' => '+775-149-3030',
                'email' => 'N.Akzholov@oms.kmg.kz',
                'status' => true,
                'sort' => 57,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Инженер по охране труда и технике безопасности',
                'position_kz' => 'Инженер по охране труда и технике безопасности',
                'full_name' => 'Бекембаева Макбал Ильясовна',
                'phone_number' => '+7 729 349 31 64',
                'internal_number' => '164',
                'mobile_number' => '+701-405-6465',
                'email' => 'M.Bekembaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 58,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Ст. инж. ОТиТБ',
                'position_kz' => 'Ст. инж. ОТиТБ',
                'full_name' => 'Сагыев Отеген Ургенчбайулы',
                'phone_number' => '+7 729 349 32 06',
                'internal_number' => '206',
                'mobile_number' => '+778-000-0603',
                'email' => 'O.Sagiev@oms.kmg.kz',
                'status' => true,
                'sort' => 59,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Ст. инж. ОТиТБ',
                'position_kz' => 'Ст. инж. ОТиТБ',
                'full_name' => 'Джасманов Марат Избасарович',
                'phone_number' => '+7 729 349 31 59',
                'internal_number' => '159',
                'mobile_number' => '+777-225-2489',
                'email' => 'M.Dzhasmanov@oms.kmg.kz',
                'status' => true,
                'sort' => 60,
            ],
            [
                'category_ru' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'category_kz' => 'Отдел техники безопасности и охраны труда и окружающей среды ОТБ,ОТиОС)',
                'position_ru' => 'Инж. по охране окружающей среды',
                'position_kz' => 'Инж. по охране окружающей среды',
                'full_name' => 'Джумабаева Дина Балтабаевна',
                'phone_number' => '+7 729 349 32 24',
                'internal_number' => '224',
                'mobile_number' => '+701-486-0990',
                'email' => 'D.Dzhumabayeva@oms.kmg.kz',
                'status' => true,
                'sort' => 61,
            ],
            [
                'category_ru' => 'Отдел закупа',
                'category_kz' => 'Отдел закупа',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Алдабергенова Асем Бердибековна',
                'phone_number' => '+7 729 349 31 80',
                'internal_number' => '165',
                'mobile_number' => '+701-245-9191',
                'email' => 'A.Aldabergenova1@oms.kmg.kz',
                'status' => true,
                'sort' => 62,
            ],
            [
                'category_ru' => 'Отдел закупа',
                'category_kz' => 'Отдел закупа',
                'position_ru' => 'Зам. начальника отдела',
                'position_kz' => 'Зам. начальника отдела',
                'full_name' => 'Рахманбердиев Самат Жеткизгенович',
                'phone_number' => '+7 729 349 31 65',
                'internal_number' => '181',
                'mobile_number' => '+777-920-0111',
                'email' => 'S.Rahmanberdiev@oms.kmg.kz',
                'status' => true,
                'sort' => 63,
            ],
            [
                'category_ru' => 'Отдел закупа',
                'category_kz' => 'Отдел закупа',
                'position_ru' => 'Ведущий специалист',
                'position_kz' => 'Жетекші маман',
                'full_name' => 'Сузакбаев Довлет Мухаммединович',
                'phone_number' => '+7 729 349 32 06',
                'internal_number' => '206',
                'mobile_number' => '+778-000-0603',
                'email' => 'D.Suzakbaev@oms.kmg.kz',
                'status' => true,
                'sort' => 64,
            ],
            [
                'category_ru' => 'Отдел логистики и МТС',
                'category_kz' => 'Отдел логистики и МТС',
                'position_ru' => 'Начальник отдела (МТС)',
                'position_kz' => 'Начальник отдела (МТС)',
                'full_name' => 'Есенжан Сарсенбай Каукенулы',
                'phone_number' => '+7 729 349 32 01',
                'internal_number' => '201',
                'mobile_number' => '+777-111-9868',
                'email' => 'S.Yessenzhan@oms.kmg.kz',
                'status' => true,
                'sort' => 65,
            ],
            [
                'category_ru' => 'Отдел логистики и МТС',
                'category_kz' => 'Отдел логистики и МТС',
                'position_ru' => 'Ведущий специалист (МТС)',
                'position_kz' => 'Ведущий специалист (МТС)',
                'full_name' => 'Аманжолов Артык Алданазарович',
                'phone_number' => '+7 729 349 31 98',
                'internal_number' => '198',
                'mobile_number' => '+777-664-4401',
                'email' => 'A.Amanzholov1@oms.kmg.kz',
                'status' => true,
                'sort' => 66,
            ],
            [
                'category_ru' => 'Отдел логистики и МТС',
                'category_kz' => 'Отдел логистики и МТС',
                'position_ru' => 'Специалист (МТС)',
                'position_kz' => 'Специалист (МТС)',
                'full_name' => 'Темирова Нурслу Талбаевна',
                'phone_number' => '+7 729 349 31 82',
                'internal_number' => '182',
                'mobile_number' => '+701-243-8268',
                'email' => 'N.Temirova@oms.kmg.kz',
                'status' => true,
                'sort' => 67,
            ],
            [
                'category_ru' => 'Отдел логистики и МТС',
                'category_kz' => 'Отдел логистики и МТС',
                'position_ru' => 'Инженер (по логистике)',
                'position_kz' => 'Инженер (по логистике)',
                'full_name' => 'Давишев Берик Жанбрбаевич',
                'phone_number' => '+7 729 349 32 05',
                'internal_number' => '205',
                'mobile_number' => '+700-120-2077',
                'email' => 'B.Davishev@oms.kmg.kz',
                'status' => true,
                'sort' => 68,
            ],
            [
                'category_ru' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'category_kz' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'position_ru' => 'Начальник отдела',
                'position_kz' => 'Начальник отдела',
                'full_name' => 'Аманғали Сарсенбай Сатанұлы',
                'phone_number' => '+7 729 349 31 40',
                'internal_number' => '140',
                'mobile_number' => '+701-999-8434',
                'email' => 'S.Amangali@oms.kmg.kz',
                'status' => true,
                'sort' => 69,
            ],
            [
                'category_ru' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'category_kz' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'position_ru' => 'Ведущий инженер по соц. вопросам',
                'position_kz' => 'Ведущий инженер по соц. вопросам',
                'full_name' => 'Мынбаева Гульмира Байлыевна',
                'phone_number' => '+7 729 349 31 92',
                'internal_number' => '192',
                'mobile_number' => '+701-188-8959',
                'email' => 'G.Mynbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 70,
            ],
            [
                'category_ru' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'category_kz' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'position_ru' => 'Инженер по соц. вопросам',
                'position_kz' => 'Инженер по соц. вопросам',
                'full_name' => 'Инкарова Саида Еркиновна',
                'phone_number' => '+7 729 349 31 91',
                'internal_number' => '191',
                'mobile_number' => '+701-577-4141',
                'email' => 'S.Inkarova@oms.kmg.kz',
                'status' => true,
                'sort' => 71,
            ],
            [
                'category_ru' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'category_kz' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'position_ru' => 'Инженер (АХО)**',
                'position_kz' => 'Инженер (АХО)**',
                'full_name' => 'Есенжанова Гүлнұр Сарсенбайқызы',
                'phone_number' => '+7 729 349 31 69',
                'internal_number' => '169',
                'mobile_number' => '',
                'email' => 'G.Yessenzhanova@oms.kmg.kz',
                'status' => true,
                'sort' => 72,
            ],
            [
                'category_ru' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'category_kz' => 'Отдел социальной политики и хозяйственного обеспечения (ОСПиХО)',
                'position_ru' => 'Ведущий инженер по соц. вопросам',
                'position_kz' => 'Ведущий инженер по соц. вопросам',
                'full_name' => 'Кокушев Нурлан Куандыкович',
                'phone_number' => '+7 729 349 31 37',
                'internal_number' => '137',
                'mobile_number' => '+7702-397-9292',
                'email' => 'N.Kokushev@oms.kmg.kz',
                'status' => true,
                'sort' => 73,
            ],
            [
                'category_ru' => 'Профсоюз',
                'category_kz' => 'Профсоюз',
                'position_ru' => 'Бухгалтер "Жондеу"',
                'position_kz' => 'Бухгалтер "Жондеу"',
                'full_name' => 'Есенкулова Нурсауле',
                'phone_number' => '+7 729 349 32 26',
                'internal_number' => '226',
                'mobile_number' => '+708-811-6310',
                'email' => 'Zhondeu.profsoyuz@mail.ru',
                'status' => true,
                'sort' => 74,
            ],
            [
                'category_ru' => 'Профсоюз',
                'category_kz' => 'Профсоюз',
                'position_ru' => 'Секретарь "ОМС"',
                'position_kz' => 'Секретарь "ОМС"',
                'full_name' => 'Омарова Регина Кадыровна',
                'phone_number' => '+7 729 349 32 27',
                'internal_number' => '227',
                'mobile_number' => '+700-745-4206',
                'email' => 'Profsoyuz_oms@mail.ru',
                'status' => true,
                'sort' => 75,
            ],
            [
                'category_ru' => 'Профсоюз',
                'category_kz' => 'Профсоюз',
                'position_ru' => 'Секретарь "Шаңырақ"',
                'position_kz' => 'Секретарь "Шаңырақ"',
                'full_name' => 'Сагындыкова Назерке Рахметоллақызы',
                'phone_number' => '+7 729 349 32 16',
                'internal_number' => '216',
                'mobile_number' => '+707-424-3143',
                'email' => 'Sanyrak2022x@mail.ru',
                'status' => true,
                'sort' => 76,
            ],
            [
                'category_ru' => 'Диспечер ЦИТС',
                'category_kz' => 'Диспечер ЦИТС',
                'position_ru' => 'Диспечер ЦИТС- 1',
                'position_kz' => 'Диспечер ЦИТС- 1',
                'full_name' => 'Диспечер БПО 1',
                'phone_number' => '+7 729 349 32 18',
                'internal_number' => '218',
                'mobile_number' => '',
                'email' => 'Dispetcher1@oms.kmg.kz',
                'status' => true,
                'sort' => 77,
            ],
            [
                'category_ru' => 'Диспечер ЦИТС',
                'category_kz' => 'Диспечер ЦИТС',
                'position_ru' => 'Диспечер ЦИТС- 2 (ЦДНГ-3)',
                'position_kz' => 'Диспечер ЦИТС- 2 (ЦДНГ-3)',
                'full_name' => 'Диспечер БПО 2',
                'phone_number' => '+7 729 349 31 51',
                'internal_number' => '151',
                'mobile_number' => '',
                'email' => 'Dispetcher2@oms.kmg.kz',
                'status' => true,
                'sort' => 78,
            ],
            [
                'category_ru' => 'ЦИТС-1, БПО',
                'category_kz' => 'ЦИТС-1, БПО',
                'position_ru' => 'Экономист Автоколонны ИТР',
                'position_kz' => 'Экономист Автоколонны ИТР',
                'full_name' => 'Конырбаева Мейрамгул Бигеновна',
                'phone_number' => '+7 729 349 32 28',
                'internal_number' => '228',
                'mobile_number' => '+705-880-7171',
                'email' => 'M.Konirbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 79,
            ],
            [
                'category_ru' => 'ЦИТС-1, БПО',
                'category_kz' => 'ЦИТС-1, БПО',
                'position_ru' => 'Заведующий складом',
                'position_kz' => 'Заведующий складом',
                'full_name' => 'Ишанбаева Алмагул Оспановна',
                'phone_number' => '+7 729 349 32 07',
                'internal_number' => '207',
                'mobile_number' => '',
                'email' => '',
                'status' => true,
                'sort' => 80,
            ],
            [
                'category_ru' => 'ЦИТС-2',
                'category_kz' => 'ЦИТС-2',
                'position_ru' => 'Заместитель руководителя службы',
                'position_kz' => 'Қызмет басшысының орынбасары',
                'full_name' => 'Мухаммедзянов Артур Гусманович',
                'phone_number' => '+7 729 349 31 75',
                'internal_number' => '175',
                'mobile_number' => '+777-599-4274',
                'email' => 'A.Muhammedziyanov@oms.kmg.kz',
                'status' => true,
                'sort' => 81,
            ],
            [
                'category_ru' => 'ЦИТС-2',
                'category_kz' => 'ЦИТС-2',
                'position_ru' => 'Экономист Цеха КРС',
                'position_kz' => 'Экономист Цеха КРС',
                'full_name' => 'Темирбаева Айдана Нуржигитовна',
                'phone_number' => '+7 729 349 32 21',
                'internal_number' => '221',
                'mobile_number' => '+771-894-6517',
                'email' => 'A.Temirbaeva@oms.kmg.kz',
                'status' => true,
                'sort' => 82,
            ],
            [
                'category_ru' => 'ЦИТС-2',
                'category_kz' => 'ЦИТС-2',
                'position_ru' => 'Экономист Цеха КРС',
                'position_kz' => 'Экономист Цеха КРС',
                'full_name' => 'Отеекева Шолпан Велиевна',
                'phone_number' => '+7 729 349 31 41',
                'internal_number' => '141',
                'mobile_number' => '+775-655-8833',
                'email' => 'Sh.Otekeeva@oms.kmg.kz',
                'status' => true,
                'sort' => 83,
            ],
            [
                'category_ru' => 'БПО',
                'category_kz' => 'БПО',
                'position_ru' => 'Заведующий складом',
                'position_kz' => 'Заведующий складом',
                'full_name' => 'Есенжан Максат Сарсенбаевич',
                'phone_number' => '+7 729 349 32 15',
                'internal_number' => '215',
                'mobile_number' => '+775-255-3444',
                'email' => 'M.Yessenzhan@oms.kmg.kz',
                'status' => true,
                'sort' => 84,
            ],
            [
                'category_ru' => 'Группа по управлению производственными отношениями',
                'category_kz' => 'Группа по управлению производственными отношениями',
                'position_ru' => 'Руководитель ГУПО',
                'position_kz' => 'Руководитель ГУПО',
                'full_name' => 'Айдарбаев Нургали Жоламанулы',
                'phone_number' => '+7 729 349 31 67',
                'internal_number' => '167',
                'mobile_number' => '+708-959-1017',
                'email' => 'N.Aidarbayev1@oms.kmg.kz',
                'status' => true,
                'sort' => 85,
            ],
            [
                'category_ru' => 'Группа по управлению производственными отношениями',
                'category_kz' => 'Группа по управлению производственными отношениями',
                'position_ru' => 'Ведущий специалист',
                'position_kz' => 'Жетекші маман',
                'full_name' => 'Қалиев Сәндібек Чашембайұлы',
                'phone_number' => '+7 729 349 31 74',
                'internal_number' => '174',
                'mobile_number' => '+778-443-1377',
                'email' => 'S.Kaliev@oms.kmg.kz',
                'status' => true,
                'sort' => 86,
            ],
            [
                'category_ru' => 'Группа по управлению производственными отношениями',
                'category_kz' => 'Группа по управлению производственными отношениями',
                'position_ru' => 'Специалист',
                'position_kz' => 'Маман',
                'full_name' => 'Асабаева Гулпаршын Алмаметовна',
                'phone_number' => '',
                'internal_number' => '',
                'mobile_number' => '+702-965-96-99',
                'email' => 'G.Asabayeva@oms.kmg.kz',
                'status' => true,
                'sort' => 87,
            ],
        ];

        foreach ($contacts as $contact) {
            Contact::create($contact);
        }

        $this->command->info('Contacts seeded successfully! Total: ' . count($contacts));
    }
}
